require("colors")
require("keymaps")
require("options")
require("plugins")

require("rcplugins.dap")
require("rcplugins.lsp")

require("rcplugins.bufferline")
require("rcplugins.commentary")
require("rcplugins.nvim_cmp")
require("rcplugins.gitsigns")
require("rcplugins.harpoon")
require("rcplugins.lsp_lines")
require("rcplugins.lualine")
require("rcplugins.nvim_tree")
require("rcplugins.telescope")
require("rcplugins.toggleterm")
require("rcplugins.treesitter")
