require("plugins")
require("colors")
require("keymaps")
require("options")

-- require("rcplugins.dap")
-- require("rcplugins.lsp")

require('rcplugins.lspconfig')

require("rcplugins.bufferline")
require("rcplugins.comment")
require("rcplugins.dap")
require("rcplugins.nvim_cmp")
require("rcplugins.gitsigns")
require("rcplugins.harpoon")
require("rcplugins.ibl")
require("rcplugins.lualine")
require("rcplugins.nvim_tree")
require("rcplugins.rest")
require("rcplugins.telescope")
require("rcplugins.toggleterm")
require("rcplugins.treesitter")
